export const HERO_POWER_ASSET_KEYS = [
  'hero-power-druid',
  'hero-power-hunter',
  'hero-power-mage',
  'hero-power-paladin',
  'hero-power-paladin-tidal-hand',
  'hero-power-priest',
  'hero-power-mind-spike',
  'hero-power-mind-shatter',
  'hero-power-rogue',
  'hero-power-shaman',
  'hero-power-warlock',
  'hero-power-warrior',
  'hero-power-deaths-shadow',
  'hero-power-plague-lord',
  'hero-power-build-a-beast',
  'hero-power-bladestorm',
  'hero-power-icy-touch',
  'hero-power-the-four-horsemen',
  'hero-power-voidform',
  'hero-power-transmute-spirit',
  'hero-power-siphon-life',
  'hero-power-ossirian-tear',
  'hero-power-pharaohs-warmask',
  'hero-power-ascendant-scroll',
  'hero-power-emperor-wraps',
  'hero-power-obelisks-eye',
  'hero-power-ancient-blades',
  'hero-power-heart-of-virnaal',
  'hero-power-tome-of-origination',
  'hero-power-anraphets-core',
  'hero-power-druid-upgraded',
  'hero-power-hunter-upgraded',
  'hero-power-mage-upgraded',
  'hero-power-paladin-upgraded',
  'hero-power-priest-upgraded',
  'hero-power-rogue-upgraded',
  'hero-power-shaman-upgraded',
  'hero-power-warlock-upgraded',
  'hero-power-warrior-upgraded',
  'hero-power-jaraxxus',
  'hero-power-ragnaros'
] as const

export type HeroPowerAssetKey = (typeof HERO_POWER_ASSET_KEYS)[number]
