/** Zero-based numeric tokens that describe this spell's scalable damage.
 * Explicit bindings avoid changing healing, Overload, targets, or referenced cards.
 * Values stay in rulesText, so authored balance adjustments remain authoritative.
 */
export const SPELL_DAMAGE_TEXT_NUMBERS: Readonly<Record<string, readonly number[]>> = {
  basic_arcane_explosion: [0],
  basic_arcane_missiles: [0],
  basic_arcane_shot: [0],
  basic_backstab: [0],
  basic_cleave: [0],
  basic_consecration: [0],
  basic_drain_life: [0],
  basic_fan_of_knives: [0],
  basic_fireball: [0],
  basic_flamestrike: [0],
  basic_frost_shock: [0],
  basic_frostbolt: [0],
  basic_hammer_of_wrath: [0],
  basic_hellfire: [0],
  basic_holy_smite: [0],
  basic_mind_blast: [0],
  basic_mortal_coil: [0],
  basic_multi_shot: [0],
  basic_shadow_bolt: [0],
  basic_shiv: [0],
  basic_sinister_strike: [0],
  basic_soulfire: [0],
  basic_starfire: [0],
  basic_swipe: [0, 1],
  basic_whirlwind: [0],
  blackrock_mountain_quick_shot: [0],
  blackrock_mountain_dragons_breath: [0],
  blackrock_mountain_lava_shock: [0],
  blackrock_mountain_demonwrath: [0],
  blackrock_mountain_revenge: [0, 2],
  classic_avenging_wrath: [0],
  classic_bane_of_doom: [0],
  classic_barrel_toss: [0],
  classic_blizzard: [0],
  classic_cone_of_cold: [0],
  classic_demonfire: [0],
  classic_earth_shock: [0],
  classic_eviscerate: [0, 1],
  classic_explosive_shot: [0, 1],
  classic_explosive_trap: [0],
  classic_flame_burst: [0],
  classic_forked_lightning: [0],
  classic_headcrack: [0],
  classic_hogger_smash: [0],
  classic_holy_fire: [0],
  classic_holy_nova: [0],
  classic_ice_lance: [0],
  classic_inner_rage: [0],
  classic_kill_command: [0, 1],
  classic_lava_burst: [0],
  classic_lightning_bolt: [0],
  classic_lightning_storm: [0, 1],
  classic_moonfire: [0],
  classic_mortal_strike: [0, 2],
  classic_pyroblast: [0],
  classic_slam: [0],
  classic_snipe: [0],
  classic_starfall: [0, 1],
  classic_stomp: [0],
  classic_wrath: [0, 1],
  classic_ysera_awakens: [0],
  classic_moonfire_choose_one: [0],
  classic_wrath_damage: [0],
  classic_wrath_draw: [0],
  classic_starfall_single: [0],
  classic_starfall_all: [0],
  goblins_vs_gnomes_cobra_shot: [0],
  goblins_vs_gnomes_flamecannon: [0],
  goblins_vs_gnomes_crackle: [0, 1],
  goblins_vs_gnomes_darkbomb: [0],
  goblins_vs_gnomes_imp_losion: [0, 1],
  goblins_vs_gnomes_demonheart: [0],
  goblins_vs_gnomes_burrowing_mine: [0],
  league_of_explorers_dart_trap: [0],
  league_of_explorers_forgotten_torch: [0],
  league_of_explorers_excavated_evil: [0],
  league_of_explorers_roaring_torch: [0],
  league_of_explorers_cursed: [0],
  league_of_explorers_ancient_curse: [0],
  league_of_explorers_timepiece_of_horror: [0],
  the_grand_tournament_living_roots: [0],
  the_grand_tournament_powershot: [0],
  the_grand_tournament_arcane_blast: [0],
  the_grand_tournament_flame_lance: [0],
  the_grand_tournament_elemental_destruction: [0, 1],
  the_grand_tournament_fist_of_jaraxxus: [0],
  the_grand_tournament_bash: [0],
  the_grand_tournament_living_roots_damage: [0]
}
